theme: jekyll-theme-slate

name: [VBM]
title: [Véronique Bazier-Matte]
description: [Étudiante au doctorat sous la supervision de Hugh Thomas au [LaCIM](http://lacim.uqam.ca/) à l'[Université du Québec à Montréal](https://etudier.uqam.ca/) depuis 2016]
